export { default as LandingPage } from './LandingPage/LandingPage';
export { default as UsersPage } from './UsersPage/UsersPage';
export { default as UserPage } from './UserPage/UserPage';
export { default as EditUserPage } from './EditUserPage/EditUserPage';
export { default as PlayPage } from './PlayPage/PlayPage';
export { default as ChatPage } from './ChatPage/ChatPage';
export { default as ComponentsBookPage } from './ComponentsBookPage/ComponentsBookPage';
export { default as EditAvatarPage } from './EditAvatarPage/EditAvatarPage';
export { default as Login } from './Login/Login';
