export { default as Landing } from './Landing/Landing';
export { default as Users } from './Users/Users';
export { default as UserPage } from './UserPage/UserPage';
export { default as EditUserPage } from './EditUserPage/EditUserPage';
export { default as Play } from './Play/Play';
export { default as Chat } from './Chat/Chat';
export { default as ComponentsBook } from './ComponentsBook/ComponentsBook';
export { default as EditAvatarPage } from './EditAvatarPage/EditAvatarPage';
export { default as Login } from './Login/Login';
