version: "3.4"
services:
  test-db:
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ft_transcendence
  memcached:
    image: memcached:1.6.17-alpine3.17
    restart: always
    ports:
      - "11212:11211"
