version: "3.4"
services:
  test-db:
    image: postgres:14.4-alpine3.16
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ../db/fill-db.sh:/docker-entrypoint-initdb.d/fill-db.sh
      - ../db/setup/:/var/lib/postgresql/setup/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ft_transcendence
  memcached:
    image: memcached:1.6.15-alpine3.16
    restart: always
    ports:
      - "11212:11211"
