version: "3.4"
services:
  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    depends_on:
      - "webapp"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  webapp:
    restart: always
    depends_on:
      - "transcendence-app"

  transcendence-app:
    restart: always
    depends_on:
      - "db"
      - "memcached"

  db:
    image: postgres:14.2-alpine3.15
    restart: always
    volumes:
      - transcendence-db:/var/lib/postgresql/data

  memcached:
    image: memcached:1.6.15-alpine3.15

volumes:
  transcendence-db:
