version: "3.4"
services:
  migrations:
    image: ft_transcendence/transcendence-app-dev
    build:
      context: .
      dockerfile: ./transcendence-app/Dockerfile
      target: development
    volumes:
      - transcendence-app-data-dev:${TRANSCENDENCE_APP_DATA:-/var/lib/transcendence-app}
      - ./transcendence-app/src:/service/transcendence-app/src:ro
      - ./transcendence-app/migrations:/service/transcendence-app/migrations:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - WEBSITE_OWNER_PASSWORD=admin
      - WEBSITE_OWNER_USERNAME=admin
    command: npm run knex:migrate:dev -w transcendence-app

  db:
    volumes:
      - transcendence-db-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  transcendence-db-dev:
  transcendence-app-data-dev:
