version: "3.4"
services:
  nginx:
    ports:
      - "80:80"

  webapp:
    image: ft_transcendence/webapp-prod
    build:
      context: ./webapp
      target: production
      args:
        - REACT_APP_NAME=webapp-prod
    volumes:
      - ./nginx/webapp.conf:/etc/nginx/conf.d/default.conf:ro

  transcendence-app:
    image: ft_transcendence/transcendence-app-prod
    build:
      context: ./transcendence-app
      target: production
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?required}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?required}
      - FORTYTWO_APP_CALLBACK_URL=${FORTYTWO_APP_CALLBACK_URL:?required}
      - WEBSITE_OWNER_PASSWORD=123

  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?required}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?required}
