version: "3.4"
services:
  migrations:
    depends_on:
      db:
        condition: service_healthy
    build:
      args:
        - TRANSCENDENCE_APP_DATA=${TRANSCENDENCE_APP_DATA:-/var/lib/transcendence-app}
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ft_transcendence

  db:
    image: postgres:14.7-alpine3.17
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=ft_transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
