version: "3.4"
services:
  nginx:
    ports:
      - "3000:80"

  webapp:
    image: ft_transcendence/webapp-dev
    build:
      context: ./webapp
      target: development
    volumes:
      - ./webapp/src:/webapp/src:ro
    environment:
      - REACT_APP_NAME=webapp-dev
      - PORT=80
      - WDS_SOCKET_PORT=0

  transcendence-app:
    image: ft_transcendence/transcendence-app-dev
    build:
      context: ./transcendence-app
      target: development
    volumes:
      - ./transcendence-app:/transcendence-app
      - /transcendence-app/node_modules
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
