version: "3.4"
services:
  nginx:
    ports:
      - "80:80"

  webapp:
    build:
      context: ./webapp
      target: production
      args:
        - REACT_APP_NAME=webapp-prod

  transcendence-app:
    build:
      context: ./transcendence-app
      target: production
    environment:
      - TRANSCENDENCE_APP_NAME=transcendence-app-prod

  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ft_transcendence
