version: "3.4"
services:
  nginx:
    image: nginx:1.22.0-alpine
    restart: always
    depends_on:
      - "webapp"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf

  webapp:
    restart: always
    depends_on:
      - "transcendence-app"

  transcendence-app:
    restart: always
    depends_on:
      - "db"
      - "memcached"
    build:
      args:
        - TRANSCENDENCE_APP_DATA=${TRANSCENDENCE_APP_DATA:-/var/lib/transcendence-app}
    volumes:
      - transcendence-app-data:${TRANSCENDENCE_APP_DATA:-/var/lib/transcendence-app}
    environment:
      - FORTYTWO_APP_AUTHORIZATION_URL=https://api.intra.42.fr/oauth/authorize
      - FORTYTWO_APP_TOKEN_URL=https://api.intra.42.fr/oauth/token
      - FORTYTWO_APP_PROFILE_URL=https://api.intra.42.fr/v2/me
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ft_transcendence

  db:
    image: postgres:14.4-alpine3.16
    restart: always
    user: postgres
    volumes:
      - transcendence-db:/var/lib/postgresql/data
      - ./db/fill-db.sh:/docker-entrypoint-initdb.d/fill-db.sh
      - ./db/setup/:/var/lib/postgresql/setup/
    environment:
      - POSTGRES_DB=ft_transcendence

  memcached:
    image: memcached:1.6.15-alpine3.16
    restart: always

volumes:
  transcendence-db:
  transcendence-app-data:
