version: "3.4"
services:
  nginx:
    image: nginx:1.22.0-alpine
    restart: always
    depends_on:
      - "webapp"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  webapp:
    restart: always
    depends_on:
      - "transcendence-app"

  transcendence-app:
    restart: always
    depends_on:
      - "db"
      - "memcached"

  db:
    image: postgres:14.4-alpine3.16
    restart: always
    user: postgres
    volumes:
      - transcendence-db:/var/lib/postgresql/data
      - ./db/fill-db.sh:/docker-entrypoint-initdb.d/fill-db.sh
      - ./db/setup/:/var/lib/postgresql/setup/

  memcached:
    image: memcached:1.6.15-alpine3.16

volumes:
  transcendence-db:
