version: "3.4"
services:
  nginx:
    ports:
      - "3000:80"

  webapp:
    image: ft_transcendence/webapp-dev
    build:
      context: ./webapp
      target: development
    volumes:
      - ./webapp/src:/webapp/src:ro
    environment:
      - REACT_APP_NAME=webapp-dev
      - PORT=80
      - WDS_SOCKET_PORT=0

  transcendence-app:
    image: ft_transcendence/transcendence-app-dev
    build:
      context: ./transcendence-app
      target: development
    volumes:
      - transcendence-app-data-dev:${TRANSCENDENCE_APP_DATA:-/var/lib/transcendence-app}
      - ./transcendence-app/src:/transcendence-app/src:ro
      - ./transcendence-app/test:/transcendence-app/test:ro
      - ./transcendence-app/seeds:/transcendence-app/seeds:ro
      - ./transcendence-app/migrations:/transcendence-app/migrations:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - WEBSITE_OWNER_PASSWORD=admin
      - WEBSITE_OWNER_USERNAME=admin
      - FORTYTWO_APP_CALLBACK_URL=http://localhost:3000/api/v1/auth/login

  db:
    volumes:
      - transcendence-db-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pg-admin:
    image: ft_transcendence/pgadmin
    build: ./pg-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    volumes:
    - ./pg-admin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:5050"

volumes:
  transcendence-db-dev:
  transcendence-app-data-dev:
