version: "3.4"
services:
  nginx:
    ports:
      - "80:80"

  transcendence-app:
    build:
      context: ./transcendence-app
      target: production

  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
