const API_ENDPOINT_URL = '/api/v1';
export const USER_URL = '/user';
export const USERS_URL = '/users';
export const USERS_EP_URL = `${API_ENDPOINT_URL}${USERS_URL}`;
export const PLAY_URL = '/play';
export const CHAT_URL = '/chat';
export const COMPONENTS_BOOK_URL = '/components-book';
export const WILDCARD_AVATAR_URL = 'https://i.pravatar.cc/9000';
export const LOGIN_EP_URL = `${API_ENDPOINT_URL}/auth/login`;
