version: "3.4"
services:
  swagger:
    image: ft_transcendence/swagger
    build:
      context: ../transcendence-app
      target: swagger
    volumes:
      - transcendence-app-data:${TRANSCENDENCE_APP_DATA:-/var/lib/transcendence-app}
      - ../transcendence-app/swagger-spec:/transcendence-app/swagger-spec
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - FORTYTWO_APP_CALLBACK_URL=http://localhost:3000/api/v1/auth/login
      - FORTYTWO_APP_AUTHORIZATION_URL=https://api.intra.42.fr/oauth/authorize
      - FORTYTWO_APP_TOKEN_URL=https://api.intra.42.fr/oauth/token
      - FORTYTWO_APP_PROFILE_URL=https://api.intra.42.fr/v2/me
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ft_transcendence
      - SESSION_SECRET=80fbbf31-7083-419a-8fe1-23f1e10aae80
      - MEMCACHED_SECRET=c9caf57b-6a21-415f-946e-b96c6b372fe5
      - FORTYTWO_APP_ID=42-intra-app-id
      - FORTYTWO_APP_SECRET=42-intra-app-secret
      - NODE_ENV=test

volumes:
  transcendence-app-data:
