name: Deploy to DigitalOcean

on:
  pull_request:
    types:
      - closed
    branches: [$default-branch]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_SSH_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: cd /srv/ft_transcendence && git pull && make prod-re
