name: migrations check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          cache: 'npm'
          cache-dependency-path: |
            ./package-lock.json
      - name: Test migrations dev
        run: |
          set -euo pipefail;
          for _ in $(seq 1 300); do
            docker-compose up --build 2>&1 & PID=$!;
            while ! { docker ps | grep migration > /dev/null ; } do \
              sleep 0.2;
            done && \
            while { docker ps | grep migration > /dev/null ; } do \
                sleep 0.2;
            done && \
            kill -s SIGINT $PID && \
            while ! { ps -aux | grep $PID > /dev/null ; } do \
                sleep 0.2;
            done && docker-compose down && docker volume prune -f \
            || break
          done
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          FORTYTWO_APP_ID: ${{ secrets.FORTYTWO_APP_ID }}
          FORTYTWO_APP_SECRET: ${{ secrets.FORTYTWO_APP_SECRET }}
          FORTYTWO_APP_CALLBACK_URL: ${{ secrets.FORTYTWO_APP_CALLBACK_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MEMCACHED_SECRET: ${{ secrets.MEMCACHED_SECRET }}
          WEBSITE_OWNER_PASSWORD: ${{ secrets.WEBSITE_OWNER_PASSWORD }}
          WEBSITE_OWNER_USERNAME: ${{ secrets.WEBSITE_OWNER_USERNAME }}
