name: packages check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'npm'
          cache-dependency-path: |
            ./package-lock.json
      - name: Install dependencies
        run: npm install -w packages/pong-engine
      - name: Build packages
        run: npm run build-packages
      - name: Lint
        run: npm run lint -w packages/pong-engine
