name: packages check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          cache: 'npm'
          cache-dependency-path: |
            ./package-lock.json
      - name: Install dependencies
        run: |
          for workspace in $(ls packages); do npm install -w packages/${workspace}; done
      - name: Build packages
        run: npm run build-packages
      - name: Lint
        run: |
          for workspace in $(ls packages); do npm run lint -w packages/${workspace}; done
