name: production run check

on:
  push:
    branches: [$default-branch]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Run
        run: make prod && make prod-down
