name: style check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'npm'
          cache-dependency-path: |
            ./package-lock.json
      - name: Install global dependencies
        run: npm install --workspaces=false
      - name: Check webapp style
        run: npm run style -w webapp
      - name: Check transcendence-app style
        run: npm run style -w webapp
      - name: Check packages style
        run: npm run style -w packages/pong-engine
      # - name: Lint
      #   run: npm run lint -w webapp
