name: transcendence-app check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          cache: 'npm'
          cache-dependency-path: |
            ./package-lock.json
      - name: Install dependencies
        run: npm install -w transcendence-app
      - name: Build packages
        run: npm run build-packages
      - name: Compile
        run: npm run build -w transcendence-app
      - name: Lint
        run: npm run lint -w transcendence-app
      - name: Test
        run: npm run test -w transcendence-app
      - name: Test e2e
        run: npm run test:e2e -w transcendence-app
