name: transcendence-app check

on:
  push:
    branches: [$default-branch]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          cache: 'npm'
          cache-dependency-path: |
            transcendence-app/package-lock.json
      - name: Install dependencies
        run: npm install --prefix transcendence-app
      - name: Compile
        run: npm run build --prefix transcendence-app
      - name: Check style
        run: npm run style --prefix transcendence-app
      - name: Lint
        run: npm run lint --prefix transcendence-app
      - name: Test
        run: npm run test --prefix transcendence-app
