name: webapp check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
          cache: "npm"
          cache-dependency-path: |
            ./package-lock.json
      - name: Install dependencies
        run: npm install -w webapp
      - name: Build packages
        run: npm run build-packages
      - name: Generate code
        run: make gen
      - name: Compile
        run: npm run build -w webapp
      - name: Check style
        run: npm run style -w webapp
      - name: Lint
        run: npm run lint -w webapp
      - name: Test
        run: npm run test-ci -w webapp
