name: webapp check

on:
  push:
    branches: [$default-branch]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    steps:
      - name: Check out Github repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          cache: 'npm'
          cache-dependency-path: |
            transcendence-app/package-lock.json
            webapp/package-lock.json
      - name: Install dependencies
        run: npm install --prefix webapp
      - name: Compile
        run: npm run build --prefix webapp
      - name: Check style
        run: npm run style --prefix webapp
      - name: Lint
        run: npm run lint --prefix webapp
      - name: Test
        run: npm run test-ci --prefix webapp
